# DocuChat Configuration File
# ==============================================

# Model Configuration
# ------------------
llm_model: "llama2:7b"
embedding_model: "sentence-transformers/all-mpnet-base-v2"

# MongoDB Configuration
# -------------------
database_name: "rag_knowledge_base"
collection_name: "pdf_documents"

# Document Processing Configuration
# ---------------------------------
chunk_size: 512
chunk_overlap: 50

# Retrieval Configuration
# ----------------------
default_k: 5
default_threshold: 0.2
